### ISSUE TITLE
0.1.4 is not published

### ISSUE THREAD

**Issue by enzief** [vovapolu/scaluzzi#13]
Hello, @vovapolu (and sorry I don't know another way to contact you)!

Publishing job for latest version failed, restarting didn't help. Could you have a look please, and maybe show me how to fix if it happens again?

Issue might be related to recent `sbt-ci-release` version update.

**Comment by enzief** [comment]
@vovapolu It's really not about sbt plugins version, downgrading didn't help. I think it's a problem with Nexus credentials.
Could you give a look when you have some time please?

**Comment by vovapolu** [comment]
Sorry, I forgot I've changed my sonatype password. `0.1.4.1` is published :tada:
