### ISSUE TITLE
Publishing problem

### ISSUE THREAD

**Issue by enzief** [vovapolu/scaluzzi#14]
Hello @vovapolu would you be able to look at the CI please? Somehow a tagged version could not be published while a git-hashed one is fine.
https://github.com/vovapolu/scaluzzi/runs/1076041121

**Comment by enzief** [comment]
Ping @vovapolu

**Comment by vovapolu** [comment]
@enzief I need to renew gpg key for the CI, and for that I need to recover my password. Give me some time, if I couldn't do this I will generate new gpg key.

**Comment by vovapolu** [comment]
@enzief Can you use new 0.1.14 or 0.1.15 versions?

**Comment by enzief** [comment]
Yes, it works for me. Thank you!

**Comment by vovapolu** [comment]
@enzief Great! Build is red, but if it works, we can ignore it for now :D
