### ISSUE TITLE
Release compatible with Scalafix `0.10.0`

### ISSUE THREAD

**Issue by alejandrohdezma** [vovapolu/scaluzzi#22]
Hi! First of all thanks for these rules, they're awesome!

**The problem:**
When using this rules with version `0.10.0` of Scalafix the following message is displayed on the shell:

```
[info] Loading external rule(s) built against an old version of Scalafix (0.9.33).
[info] This might not be a problem, but in case you run into unexpected behavior, you
[info] should try a more recent version of the rules(s) if available. If that does
[info] not help, request the rule(s) maintainer to build against Scalafix 0.10.0
[info] or later, and downgrade Scalafix to 0.9.x (x>=33) for the time being.
```

**The solution:**

Since support for Scalafix `0.10.0` was added on #21 is just a matter of releasing a new version.

Thanks!

**Comment by kubukoz** [comment]
bumping, the update seems to be on master but isn't released yet - let me know how I can help.

**Comment by enzief** [comment]
Sorry I have been busy, will look tonight.

**Comment by enzief** [comment]
@alejandrohdezma @kubukoz can this be closed?

**Comment by alejandrohdezma** [comment]
Yes! Thank you!
